### PR TITLE
Update fixes.xml

### PR DESCRIPTION
**Pull request by bwjohnson92**
Addition of the Mount Status (85)

### CODE REVIEW

**Comment by z16** [comment]
One question about this, before I merge it... is that the only new status? Someone mentioned fleetingly that it was specific to a raptor mount... is that correct?

**Comment by bwjohnson92** [comment]
I've tested both Tiger and Raptor mounts. Both return 85, so I assume that's the plan for all mounts. I'm guessing they used a new status to allow them to easily play the music with it.

**Comment by bwjohnson92** [comment]
I will test again to confirm, just in case I misremembered.

**Comment by z16** [comment]
I see, I'll merge this then, thanks for the info! I won't be able to push the new resources until I get home, no idea when that'll be at this point...

**Pull request merged**
