### PR TITLE
Add a "slot" property so every addon isn't doing the same string.lowe…

### PR DESCRIPTION
**Pull request by kelhor**
…r, string.gsub dance.

If this isn't the route you'd like to go with this, that's alright, I just think it'll make life easier on addon developers (since I've seen four different addons that all do this more or less the same way, and safe 2 broke them all in different ways).

### CODE REVIEW

**Comment by IryokuChevalier** [comment]
I think this is a decent idea. I'm not thrilled about the name "slot", though; I think "key" would be a better name for this field.

@z16 what do you think?

**Comment by z16** [comment]
```
08:24 < Arcon> rooks: I'm against it personally... a) it's cleaner without that, since resources only reflect game data, not our API
08:24 < Arcon> And b) those addons should be switched to work with IDs
08:24 < Arcon> I was actually just working on a FindAll refactoring that makes it use IDs instead of bag names
08:25 < Arcon> I won't close it yet, I'd like to know Iryoku's opinion first
08:25 < Arcon> So Iryoku, consider yourself summoned
```

**Comment by IryokuChevalier** [comment]
I'm OK with it leaving this out too. If we do include it, then I think the name needs to be changed though.

**Comment by kelhor** [comment]
I'm not particularly attached to the name or the idea either way. It was a more elegant solution to a problem that comes up in a number of addons, with the bonus of potentially future proofing it for Satchel 2 coming down the pike.

I've already converted my local copy of organizer to use IDs instead, which is cleaner overall anyway.

**Pull request closed without merging**
